credentials:
  usernames:
    Samuelapp:
      email: samuel47dribsa@gmail.com
      logged_in: False # Will be managed automatically
      name: Samuel
      password: '123' # Make sure to enclose in quotes
    